language: ruby
cache: bundler

sevices:
  - postgresql

before_install:
  - createdb gemlifting_test
  - cp config/database.travis.yml config/database.yml

rvm:
  - 2.3.1

matrix:
  include:
    - rvm: 2.4.0
      gemfile: gemfiles/ruby-2.4
    - rvm: 2.5.0-dev
      gemfile: gemfiles/ruby-2.5
