GithubImporterJob:
  every:
    - "1h"
    - :first_in: '10s'
  description: "This job will update Github stats of gems."
RubygemsImporterJob:
  cron:
    - "0 0 * * 0"
    - :first_in: '5m'
  description: "This job will update Rubygems stats of gems and import new gems to database."
RubygemsSyncJob:
  every:
    - "15m"
    - :first_in: '10s'
  description: "This job adds latest new gems & updates latest updated on Rubygems."
SitemapRefreshJob:
  cron:
    - "0 05 * * *"
    - :first_in: '5s'
  description: "Daily refreshing dynamic sitemap."
RecordMetricsJob:
   cron:
    - "0 02 * * *"
    - :first_in: '5s'
   description: "Records metrics and then runs the transportation."
